name: 'CI'

on:
  push:
    branches: 
      - '*'

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  unit-test:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '9.7.1'
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build
          pnpm prepack

      - name: Run tests
        env:
          CI: true
        continue-on-error: true
        run: |
          pnpm run test --reporters="default" --reporters="summary" --reporters="jest-ctrf-json-reporter"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-ctrf-report
          path: ctrf/ctrf-report.json
          
      - name: Run CTRF annotations
        run: npx github-actions-ctrf ctrf/ctrf-report.json
        if: always()

  int-test:
    runs-on: 'ubuntu-latest'

    services:
      firestore:
        image: preisvergleich/gcloud-firestore:889
        #
        ports:
          - 8080:8086
          
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '9.7.1'
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: See if Emulator runs
        run: |
          curl -v  http://localhost:8080/

      - name: Install adapter dependencies and build
        run: |
          pnpm install
          pnpm build
          pnpm prepack

      - name: Install test app dependencies
        run: |
          cd dev
          pnpm install

      - name: Run tests
        env:
          CI: true
        continue-on-error: true
        run: |
          cd dev
          pnpm run test --reporters="default" --reporters="summary" --reporters="jest-ctrf-json-reporter"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: int-test-ctrf-report
          path: dev/ctrf/ctrf-report.json
          
      - name: Run CTRF annotations
        run: npx github-actions-ctrf dev/ctrf/ctrf-report.json
        if: always()
      
  payload-int-test:
    runs-on: 'ubuntu-latest'

    services:
      firestore:
        image: preisvergleich/gcloud-firestore:889
        #
        ports:
          - 8080:8086
          
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '9.7.1'
          run_install: false

      - name: Checkout payload
        uses: actions/checkout@v4
        with:
          repository: payloadcms/payload
          ref: v3.9.0
          path: payload

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'pnpm'
          cache-dependency-path: 'payload/pnpm-lock.yaml'

      - name: 'Show pnpm'
        run: |2-
          pnpm --version
          node --version

      - name: "Let's see"
        run: |2-
          ls -al
          ls -al payload

      - name: See if Emulator runs
        run: |
          curl -v  http://localhost:8080/

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build
          pnpm prepack

      - name: Install dependencies for payload
        run: |
          cd payload
          pnpm install

      - name: Run tests
        env:
          CI: true
        continue-on-error: true
        run: |
          cd payload
          pnpm install --save-dev jest-ctrf-json-reporter -w
          cp ../.github/files/jest.setup.js test/jest.setup.js
          cp ../.github/files/reset.ts test/helpers/reset.ts
          cp ../.github/files/snapshot.ts test/helpers/snapshot.ts
          node_modules/.bin/cross-env NODE_OPTIONS=\"--no-deprecation\" NODE_NO_WARNINGS=1 PAYLOAD_DATABASE=firestore FIRESTORE_EMULATOR_HOST=0.0.0.0:8080 FIRESTORE_PROJECT_ID=example DISABLE_LOGGING=true node_modules/.bin/jest --forceExit --detectOpenHandles --reporters="default" --reporters="summary" --reporters="jest-ctrf-json-reporter" --config=test/jest.config.js --runInBand test/
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: payload-int-test-ctrf-report
          path: payload/ctrf/ctrf-report.json
          
      - name: Run CTRF annotations
        run: npx github-actions-ctrf payload/ctrf/ctrf-report.json
        if: always()

