name: Prerelease Alpha Version

on:
  push:
    branches:
      - main

jobs:
  prerelease:
    name: Bump Alpha Version and Create Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: pnpm install

      - name: Bump Alpha Version
        run: |
          pnpm version prerelease --preid=alpha --no-git-tag-version

      - name: Commit Version Bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: bump alpha version [skip ci]"

      - name: Create Alpha Tag and Push Changes
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag "v$VERSION"
          git push origin main --tags
          git push
