name: 'CI'

on:
  push:
    branches: 
      - '*'
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '9.7.1'
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          # cache: 'pnpm'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 490.0.0'
          install_components: 'cloud-firestore-emulator'
      
      - name: 'Show Gcloud'
        run: |2-
          gcloud info

      - name: Run Emulator in Background
        run: |
          gcloud emulators firestore start --host-port=0.0.0.0:8080 &
          FIRESTORE_EMULATOR_PID=$!
          echo "FIRESTORE_EMULATOR_PID=$FIRESTORE_EMULATOR_PID" >> $GITHUB_ENV
      - name: See if Emulator runs
        run: |
          curl -v  http://localhost:8080/
      - name: 'Show pnpm'
        run: |2-
          pnpm --version
          node --version

